### ISSUE TITLE
No Display on M5Stack

### ISSUE THREAD

**Issue by jeremyjh** [littlevgl/esp32_ili9341#18]
I [configured this library](https://github.com/jeremyjh/esp32_ili9341/commit/77de290772c6662cd5791a0a02b1c521944035ed) for the pinouts on the [M5Stack](https://github.com/m5stack/M5Stack#4-hw-reference). Built and flashed it, and judging from the INFO logs it runs through the demo just fine, there are no errors. However, nothing is ever displayed on the screen. 

These pin configurations work fine on this device with both [loboris's driver](https://github.com/loboris/ESP32_TFT_library) and with the lvgl demo using the Adafruit driver as [appropriated in the esp-iot-solution](https://github.com/espressif/esp-iot-solution/tree/master/components/spi_devices/lcd). 

I thought there must be some difference in initialization command sequence, so I even tried wedging in the init sequence from loboris's repo, but this did not work either. I'm really at a loss as to what could be going wrong, assuming this repo does currently work with other devices.

Sample output:
```
I (0) cpu_start: App cpu up.
I (308) heap_init: Initializing. RAM available for dynamic allocation:
I (315) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (321) heap_init: At 3FFC5CE0 len 0001A320 (104 KiB): DRAM
I (327) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (334) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (340) heap_init: At 4008AA58 len 000155A8 (85 KiB): IRAM
I (346) cpu_start: Pro cpu start user code
I (29) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
Info: lv_init ready 	(/Users/jeremy/esp/esp32_ili9341/components/lvgl/src/lv_core/lv_obj.c #117)
ILI9341 initialization.
Enable backlight.
Info: Screen create ready 	(/Users/jeremy/esp/esp32_ili9341/components/lvgl/src/lv_core/lv_obj.c #211)
Info: Screen create ready 	(/Users/jeremy/esp/esp32_ili9341/components/lvgl/src/lv_core/lv_obj.c #211)
Info: Screen create ready 	(/Users/jeremy/esp/esp32_ili9341/components/lvgl/src/lv_core/lv_obj.c #211)
Info: image created 	(/Users/jeremy/esp/esp32_ili9341/components/lvgl/src/lv_objx/lv_img.c #108)
Info: lv_img_set_src:  `LV_IMG_SRC_VARIABLE` type found 	(/Users/jeremy/esp/esp32_ili9341/components/lvgl/src/lv_objx/lv_img.c #152)
Info: container created 	(/Users/jeremy/esp/esp32_ili9341/components/lvgl/src/lv_objx/lv_cont.c #113)
Info: button matrix created 	(/Users/jeremy/esp/esp32_ili9341/components/lvgl/src/lv_objx/lv_btnm.c #127)
...
```

**Comment by kisvegabor** [comment]
We use GitHub Issues for development-related discussions.

Please ask your question in the [Forum](https://forumtest.littlevgl.com/) to make it visible for a larger community. You can simply log in with your GitHub account.
