### ISSUE TITLE
ili9341 PORTRAIT mode

### ISSUE THREAD

**Issue by zoon81** [littlevgl/esp32_ili9341#21]
I saw some questions about screen rotations, so I think I post my solution here.
Things to change:

[ili9341.c at line 62](https://github.com/littlevgl/esp32_ili9341/blob/83b18d690b74ede199d2f2ae2d2b725ff9d6e6d8/components/drv/ili9341.c#L62):
original:
`{0x36, {0x28}, 1},			/*Memory Access Control*/`
modify to
`{0x36, {0x48}, 1},			/*Memory Access Control*/
`

[lv_conf.h at line 24](https://github.com/littlevgl/esp32_ili9341/blob/83b18d690b74ede199d2f2ae2d2b725ff9d6e6d8/components/lv_conf.h#L24)
original:
```
#define LV_HOR_RES_MAX          (320)
#define LV_VER_RES_MAX          (240)
```
modify to:
```
#define LV_HOR_RES_MAX          (240)
#define LV_VER_RES_MAX          (320)
```

After theres simple changes the display must show portrait image.

**Comment by jeremyjh** [comment]
The LVGL library has [dynamic rotation support](https://docs.littlevgl.com/en/html/porting/display.html?highlight=rotate#display-driver); what we should do in the driver is support that rather than simply hard coding a different rotation. Whatever we hardcode will work for some and not others.
